
COMMONROOT=$$(MW_COMMON)
FRAMEWORKROOT=$$(MW_FWROOT)

MODULEPATH = $${APPROOT}/Modules
SRCPATH = $${APPROOT}/Src
IMGPATH = $${APPROOT}/Images
RCSPATH = $${APPROOT}/Resources
FORMPATH = $${APPROOT}/Forms


INCLUDEPATH += $${SRCPATH}
