
COMMONROOT=$$(MW_COMMON)
FRAMEWORKROOT=$$(MW_FWROOT)

MODULEPATH = $${APPROOT}/Modules
SRCPATH = $${APPROOT}/Src
AUTOGEN_SRCPATH = $${APPROOT}/Src_autogen
IMGPATH = $${APPROOT}/Images
RCSPATH = $${APPROOT}/Resources
FORMPATH = $${APPROOT}/Forms
SCHEMAPATH = $${APPROOT}/Schemas


INCLUDEPATH += $${SRCPATH} $${AUTOGEN_SRCPATH}
